export const anchorsArticlePT = [
  'A música contemporânea:',
  'A improvisação:',
  'Os jogos na aprendizagem:',
  'O ensino coletivo do violoncelo:',
  'Atividades práticas:',
  'Descrição do Jogo 1',
  'Descrição do Jogo 2',
  'Descrição do Jogo 3',
  'Descrição do Jogo 4',
  'Descrição do Jogo 5',
  'Descrição do Jogo 6',
  'Descrição do Jogo 7',
  'Descrição do Jogo 8',
  'Descrição do Jogo 9',
  'Descrição do Jogo 10',
  'Sugestão de repertório:',
  'Para saber mais:',
  'Referência:',
]

export const anchorsArticleES = [
  '1. Detective sonoro ES',
  '2. ¿Que sonido es ese?',
  '3. Telefone sem fio sonoro virtual',
  '4. Lego musical',
  '5. Histórias da janela',
  '6. Escrevendo a história',
  '7. Espelho, espelho meu',
  '8. Mapa musical',
  '9. Sons da saudade',
  '10. Nossa música da quarentena',
]

export const anchorsArticleEN = [
  '1. ENGLISH',
  '2. ¿Que sonido es ese?',
  '3. Telefone sem fio sonoro virtual',
  '4. Lego musical',
  '5. Histórias da janela',
  '6. Escrevendo a história',
  '7. Espelho, espelho meu',
  '8. Mapa musical',
  '9. Sons da saudade',
  '10. Nossa música da quarentena',
]
