export const anchors = [
  'A música contemporânea:',
  'A improvisação:',
  'Os jogos na aprendizagem:',
  'O ensino coletivo do violoncelo:',
  'Atividades práticas:',
  'Descrição do Jogo 1',
  'Descrição do Jogo 2',
  'Descrição do Jogo 3',
  'Descrição do Jogo 4',
  'Descrição do Jogo 5',
  'Descrição do Jogo 6',
  'Descrição do Jogo 7',
  'Descrição do Jogo 8',
  'Descrição do Jogo 9',
  'Descrição do Jogo 10',
  'Sugestão de repertório:',
  'Para saber mais:',
  'Referência:',
]
